<?php

namespace AppBundle\Entity;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository {

    public function recordsTotal() {
        $result = $this->getEntityManager()
                ->createQuery('SELECT count(p) as cnt FROM AppBundle:Customer p')
                ->getResult();
        return $result[0]["cnt"];
    }

    public function recordsFiltered($where) {
        $result = $this->getEntityManager()
                ->createQuery('SELECT count(p) as cnt FROM AppBundle:Customer p ' . $where)
                ->getResult();
        return $result[0]["cnt"];
    }

}
