<?php

namespace AppBundle\Entity;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository {

    public function recordsTotal() {
        $result = $this->getEntityManager()
                ->createQuery('SELECT count(p) as cnt FROM AppBundle:Order p')
                ->getResult();
        return $result[0]["cnt"];
    }

    public function recordsFiltered($where) {
        $result = $this->getEntityManager()
                ->createQuery('SELECT count(p) as cnt FROM AppBundle:Order` p ' . $where)
                ->getResult();
        return $result[0]["cnt"];
    }

}
